version: "3.8"
services:
  vpn_proxy:
    image: docker.io/act28/pia-openvpn-proxy
    cap_add:
      - MKNOD
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 209.222.18.218
      - 209.222.18.222
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - </path/on/host>:/config
    environment:
      - REGION=switzerland
      - USERNAME=<username>
      - PASSWORD=<password>
      - UID=<uid>
      - GID=<gid>
      - LOCAL_NETWORK=10.1.1.0/24
    networks:
      - vpn_proxy
    ports:
      - 8118:8118
    restart: always

networks:
  vpn_proxy:
