logoutput: stderr

internal: 0.0.0.0 port = 1080
external: pia
external.rotation: route

user.notprivileged: nobody
socksmethod: none
clientmethod: none

client pass {
	from: 0.0.0.0/0 to: 0.0.0.0/0
	log: error
}

socks pass {
	from: 0.0.0.0/0 to: 0.0.0.0/0
	protocol: tcp udp
}
