#!/bin/sh
set -e -u -o pipefail

[ ! -d /app/ovpn/config ] && mkdir -p /app/ovpn/config
# download and install the latest default recommended ovpn configs
wget -q https://www.privateinternetaccess.com/openvpn/openvpn-strong-tcp-nextgen.zip
unzip -uoq openvpn-strong-tcp-nextgen.zip -d /app/ovpn/config
rm -f openvpn-strong-tcp-nextgen.zip

# copy configs to user mount
mkdir -p /config/pia
cp -u /app/ovpn/config/* /config/pia/

if [ -n "$UID" -a -n "$GID" ]; then
  chown -R "$UID:$GID" /config
fi

if [ -n "$REGION" ]; then
  set -- "$@" '--config' "/config/pia/${REGION}.ovpn"
else
  echo "No OpenVPN config found in /config/pia/${REGION}.ovpn. Exiting."
  exit 1
fi

if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
  echo "$USERNAME" > auth.conf
  echo "$PASSWORD" >> auth.conf
  chmod 600 auth.conf
  set -- "$@" '--auth-nocache'
  set -- "$@" '--auth-user-pass' 'auth.conf'
else
  echo "OpenVPN credentials not set. Exiting."
  exit 1
fi

openvpn "$@"
