#!/bin/sh
set -e -u -o pipefail

# Load common VPN interface detection logic
. /opt/pia/lib/vpn-interface.sh

# Wait for either 'pia' or 'tun0' to be up before starting the proxy
until is_vpn_up "pia" || is_vpn_up "tun0"; do
    sleep 5
done

mkdir -p /config/privoxy
cp -Ru /etc/privoxy/* /config/privoxy/
sed -i "s|confdir[[:blank:]]/etc/|confdir /config/|" /config/privoxy/config
# SEC: Disable logfile
sed -i 's|^logfile|#logfile|' /config/privoxy/config

if [ -n "$UID" -a -n "$GID" ]; then
    chown -R "$UID:$GID" /config
fi

# so return traffic that went through VPN works
gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0

# start
echo "Starting Privoxy..."
exec privoxy --no-daemon /config/privoxy/config
