name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: 0 14 * * 0 # Sunday 2PM UTC = Monday 12AM AEST
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Docker image
      if: (github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/')) || github.ref == 'refs/heads/main'
      run: make docker
    - name: Push Docker image
      if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/')
      run: make docker-push
